// examples/vue/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { useDemoGhost } from "@demoghostjs/vue";
import { click, type, wait, highlight } from "demoghost";

const { play, isPlaying } = useDemoGhost();
const message = ref("");
const savedText = ref("Vue 3 Demo");

const runDemo = () => {
  play([
    click("#vue-input"),
    type("#vue-input", "Autopilot in Vue 3!"),
    wait(200),
    click("#vue-save"),
    highlight("#vue-output", { duration: 1200 })
  ]);
};

const save = () => {
  if (message.value) {
    savedText.value = message.value;
    message.value = "";
  }
};
</script>

<template>
  <div style="padding: 40px; max-width: 500px; margin: 0 auto;">
    <h2>Vue 3 Composition API Adapter</h2>
    <button @click="runDemo" :disabled="isPlaying" style="margin-bottom: 20px;">
      {{ isPlaying ? 'Playing Demo...' : 'Run Vue Demo' }}
    </button>

    <div>
      <input id="vue-input" v-model="message" placeholder="Type a message" style="padding: 8px; margin-right: 8px;" />
      <button id="vue-save" @click="save" style="padding: 8px;">Save</button>
    </div>

    <div id="vue-output" style="margin-top: 20px; font-weight: bold;">
      Output: {{ savedText }}
    </div>
  </div>
</template>

// examples/react/src/App.tsx
import React, { useState } from "react";
import { useDemoGhost } from "@demoghostjs/react";
import { click, type, wait, highlight } from "demoghost";

export const App: React.FC = () => {
  const { play, isPlaying } = useDemoGhost();
  const [items, setItems] = useState<string[]>(["Initial Project"]);
  const [text, setText] = useState("");

  const handlePlay = () => {
    play([
      click("#todo-input"),
      type("#todo-input", "Interactive React Demo"),
      wait(200),
      click("#add-btn"),
      highlight(".item:last-child", { duration: 1000 })
    ]);
  };

  const handleAdd = () => {
    if (!text) return;
    setItems([...items, text]);
    setText("");
  };

  return (
    <div style={{ padding: 40, maxWidth: 500, margin: "0 auto" }}>
      <h2>React DemoGhost Integration</h2>
      <button onClick={handlePlay} disabled={isPlaying} style={{ marginBottom: 20 }}>
        {isPlaying ? "Playing..." : "Play Live Demo"}
      </button>

      <div>
        <input
          id="todo-input"
          value={text}
          onChange={e => setText(e.target.value)}
          placeholder="New Task"
          style={{ padding: 8, marginRight: 8 }}
        />
        <button id="add-btn" onClick={handleAdd} style={{ padding: 8 }}>
          Add
        </button>
      </div>

      <ul style={{ marginTop: 20 }}>
        {items.map((item, i) => (
          <li key={i} className="item" style={{ padding: 6 }}>
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
};
